version: '3.7'

services:
  mongo:
    image: mongo:4.1-bionic
    volumes:
      - mongodb-data:/data/db

  webprotege:
    image: protegeproject/webprotege
    restart: always
    environment:
      - webprotege.mongodb.host=mongo
    ports:
      - 5000:8080
    depends_on:
      - mongo

volumes:
  mongodb-data:
